### ISSUE TITLE
1日目から参加する人のバスの時間を調べる

### ISSUE THREAD

**Issue by syou6162** [TrainingCamp2012/TrainingCamp2012#1]
利根ライナーとかを調べるとよさそう。

時刻表はあるっぽいけど、最新のものか若干怪しい...
- [土善旅館（東庄町笹川）時刻表](http://www3.ocn.ne.jp/~dozen/jikokuhy.html)

**Comment by twittoru** [comment]
最新ではないです
http://www.chibakotsu.co.jp/kousoku/pdf/tm_chosi_01.pdf

大体1時間に1本、経路によって所要時間は1時間半か2時間。料金は同じで2100円。
回数券は6枚綴りの一回当り1750円。

電車でいくと東京・上野から成田まで1時間成田から1時間の計約2時間。
京成を混ぜるとバスより安い。JRだけでも成田駅(か千葉駅)でどのみち乗り換え必須。

バス停と駅だとバス停のほうが微妙に近い。

**Comment by syou6162** [comment]
どもです!!

チェックインを3時くらい(?)にするとして、出発は1時くらいですかね。近くにコンビニがあるか怪しいので、東京で買い物は色々済ませていくようにしましょう。とすると東京の集合は12時くらいにするとよさそうかな。

電車のほうは使ったことないですが、バス停から旅館は徒歩5分くらいで近い感じです。gdgdと話しながらいきたいなら電車、睡眠でも取って準備したいならバスという感じでしょうか。

**Comment by syou6162** [comment]
水曜日中くらいを目処にしてどちらの交通手段で行くか決めましょう。どっちかじゃないと不都合とかはあんまり出ないと思うので、多数決で。syou6162はバス希望です。

**Comment by wakuteka** [comment]
バスの方が合宿っぽいしバスが良いですね

**Comment by syou6162** [comment]
多数決でバス決定しました。

時間的にお昼も一緒に食べようということになりました。以下、スケジュール概観です。
- 11:30に東京駅集合、駅構内でどこかお昼ご飯を食べる
- 12:30くらいから[ピーコックストア](http://www.peacock.co.jp/)でお菓子などを買い込む
- 13:10発のバスに乗車

現時点で上のプランで行くメンバーはsyou6162、twittoru、wakuteka、yag_aysの4人でよいかな?変更等あれば書いていってください。
