### ISSUE TITLE
お金の徴収

### ISSUE THREAD

**Issue by syou6162** [TrainingCamp2012/TrainingCamp2012#5]
一泊で7500円で、二泊組は7500 \* 2 = 15000円です。また、二日目に洋室を借りるようにしたので、追加で5000円かかります。全員で6人で割るので、833円くらいになります。

ということで
- syou6162: 15833円
- wakuteka: 15833円
- yag_ays: 15833円
- twittoru: 15833円
- y_benjo: 8333円(二泊の場合は15833円)
- iNut: 8333円

になります。最終日にsyou6162が集めるので各自準備しておいてください。お菓子その他も割り勘します、たぶん。

**Comment by wakuteka** [comment]
把握しました。端数めんどいな...

**Comment by syou6162** [comment]
ワイン、日本酒(やぐさん購入)、お菓子(benjo購入?)等のお金も割り勘しましょう。これはいぬたんきてからやったほうがいいかな。

**Comment by syou6162** [comment]
回収しました。

**Comment by syou6162** [comment]
支払い済ませました。
